//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportSampleImages.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExportSampleImages.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap checkmark {
            get {
                object obj = ResourceManager.GetObject("checkmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportButtonText {
            get {
                return ResourceManager.GetString("ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph to export.
        /// </summary>
        public static string ExportGraphMsg {
            get {
                return ResourceManager.GetString("ExportGraphMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Sample Images.
        /// </summary>
        public static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported {0} images.
        /// </summary>
        public static string FinishMsg {
            get {
                return ResourceManager.GetString("FinishMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export finished..
        /// </summary>
        public static string FinishMsgTitle {
            get {
                return ResourceManager.GetString("FinishMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported {0} image..
        /// </summary>
        public static string FinishSingleMsg {
            get {
                return ResourceManager.GetString("FinishSingleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Export Sample Images.
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep folder structure.
        /// </summary>
        public static string KeepFolderStructureCheckboxMsg {
            get {
                return ResourceManager.GetString("KeepFolderStructureCheckboxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retains the original folder/subfolder structure for graphs location..
        /// </summary>
        public static string KeepFolderStructureTooltip {
            get {
                return ResourceManager.GetString("KeepFolderStructureTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source folder contains {0} Dynamo graphs..
        /// </summary>
        public static string NotificationMsg {
            get {
                return ResourceManager.GetString("NotificationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0} out of {1} graphs..
        /// </summary>
        public static string ProcessMsg {
            get {
                return ResourceManager.GetString("ProcessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Progress_circle {
            get {
                object obj = ResourceManager.GetObject("Progress_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume previous session.
        /// </summary>
        public static string ResumeCheckboxMsg {
            get {
                return ResourceManager.GetString("ResumeCheckboxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts to resume the progress from a previous run. The progress is stored within the &apos;log.txt&apos; file in the root Target folder..
        /// </summary>
        public static string ResumeTooltip {
            get {
                return ResourceManager.GetString("ResumeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder ...
        /// </summary>
        public static string SelectFolderMsg {
            get {
                return ResourceManager.GetString("SelectFolderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current graph.
        /// </summary>
        public static string SingleExportCheckboxMsg {
            get {
                return ResourceManager.GetString("SingleExportCheckboxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports an image of the current graph. Select a target folder and check this box to enable export..
        /// </summary>
        public static string SingleExportTooltip {
            get {
                return ResourceManager.GetString("SingleExportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        public static string SourceFolderMsg {
            get {
                return ResourceManager.GetString("SourceFolderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        public static string TargetFolderMsg {
            get {
                return ResourceManager.GetString("TargetFolderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder..
        /// </summary>
        public static string UpdatePathTooltip {
            get {
                return ResourceManager.GetString("UpdatePathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string ZoomGeometryCheckboxMsg {
            get {
                return ResourceManager.GetString("ZoomGeometryCheckboxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically performs a single zoom out in the geometry background workspace..
        /// </summary>
        public static string ZoomGeometryTooltip {
            get {
                return ResourceManager.GetString("ZoomGeometryTooltip", resourceCulture);
            }
        }
    }
}
